import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";

const OPENSANS = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={OPENSANS.className}>
        <div className="bg-white mx-auto xl:max-w-7xl xl:mt-8 xl:shadow-2xl xl:rounded-4xl">
          <Header />
          <main className="max-w-xl mx-auto pt-20 lg:max-w-5xl lg:grid lg:grid-cols-2 lg:gap-4 xl:pt-0">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
