import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import Nav from "./components/Nav";
import SvgGithub from "./components/svg/SvgGithub";
import SvgLinkedin from "./components/svg/SvgLinkedin";

const OPENSANS = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={OPENSANS.className}>
        <div className="bg-white mx-auto">
          <header>
            <div className="fixed z-50 h-20 w-full bg-gray-100 p-3 border-b border-gray-300 flex items-center">
              <Nav />
              <h1 className="text-3xl">Frakano</h1>
            </div>
          </header>

          <main className="max-w-xl mx-auto pt-20 overflow-hidden">
            {children}
          </main>
          <footer className="h-16 bg-gray-100 border-t border-gray-300 flex justify-center items-center">
            <nav className="flex items-center text-gray-500">
              <a href="https://linkedin.com" className="social-link mx-2 group">
                <figure className="flex items-center group-hover:text-black group-hover:border-black">
                  <SvgGithub className="mr-1.5 fill-gray-500 group-hover:fill-black" />
                  <figcaption className="border-b border-transparent transition duration-300 group-hover:border-black">
                    Github
                  </figcaption>
                </figure>
              </a>
              <a href="https://linkedin.com" className="social-link mx-2 group">
                <figure className="flex items-center group-hover:text-black group-hover:border-black">
                  <SvgLinkedin className="mr-1.5 fill-gray-500 group-hover:fill-black" />
                  <figcaption className="border-b border-transparent transition duration-300 group-hover:border-black">
                    Linkedin
                  </figcaption>
                </figure>
              </a>
            </nav>
          </footer>
        </div>
      </body>
    </html>
  );
}
